# Some data in this file will be overwritten by `*-override.yml`. Please run `generate.sh` to update the corresponding files.

name:

on:

env:
  RUST_TOOLCHAIN: nightly-2022-05-24
  CACHE_KEY_SUFFIX: v20220524
  CARGO_TERM_COLOR: always
  RW_SQLLOGICTEST_URL: https://github.com/risinglightdb/sqllogictest-rs/releases/download/v0.3.4/sqllogictest-linux-amd64.tar.gz
  RW_CARGO_MAKE_URL: https://github.com/sagiegurari/cargo-make/releases/download/0.35.10/cargo-make-v0.35.10-x86_64-unknown-linux-musl.zip
  RW_CARGO_MAKE_DIRECTORY: cargo-make-v0.35.10-x86_64-unknown-linux-musl
  RUSTFLAGS: -D warnings
  PROTOC_NO_VENDOR: true
  AWS_ROLE_TO_ASSUME: arn:aws:iam::639303875316:role/Create-IAM-Role-for-Configure-AWS-Credentials-Role-1NF1LWROB80QG

permissions:

jobs:
  # Start 2 runners (a/b) to run build and test in parallel. Note that we also have runner C in main for release build.
  start-runner-a:
    name: ec2-start-a
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          aws-region: us-east-2
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.WUTAO_PAT }}
          ec2-image-id: ami-05a99cf0eb100c377 # github-actions (60gb gp3 ssd)
          ec2-instance-type: c5.4xlarge # 16 vCPU, 32 GB Memory, EBS
          subnet-id: subnet-59743123 # default
          security-group-id: sg-9ec32bfe # default (could have security issues)

  start-runner-b:
    name: ec2-start-b
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          aws-region: us-east-2
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.WUTAO_PAT }}
          ec2-image-id: ami-05a99cf0eb100c377 # github-actions (60gb gp3 ssd)
          ec2-instance-type: c5.4xlarge # 16 vCPU, 32 GB Memory, EBS
          subnet-id: subnet-59743123 # default
          security-group-id: sg-9ec32bfe # default (could have security issues)

  stop-runner-a:
    name: ec2-stop-a
    needs:
      - start-runner-a
      - compute-node-build-dev
      - end-to-end-risedev-dev
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          aws-region: us-east-2
      - name: Stop EC2 runner A
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.WUTAO_PAT }}
          label: ${{ needs.start-runner-a.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-a.outputs.ec2-instance-id }}
        if: ${{ always() }}

  stop-runner-b:
    name: ec2-stop-b
    needs:
      - start-runner-b
      - compute-node-test
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          aws-region: us-east-2
      - name: Stop EC2 runner B
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.WUTAO_PAT }}
          label: ${{ needs.start-runner-b.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner-b.outputs.ec2-instance-id }}
        if: ${{ always() }}
