[package]
name = "risingwave_rpc_client"
version = "0.1.7"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
log = "0.4"
madsim = "=0.2.0-alpha.3"
moka = { version = "0.8", features = ["future"] }
paste = "1"
risingwave_common = { path = "../common" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_pb = { path = "../prost" }
tokio = { version = "=0.2.0-alpha.3", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tonic = { version = "=0.2.0-alpha.3", package = "madsim-tonic" }
tracing = { version = "0.1" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
